// Font classifier — AUTO-GENERATED by scripts/train-classifier.mjs. Do not hand-edit.
// Softmax over rendered-glyph features → font category. Trained on 643 Google fonts
// (real category labels); held-out accuracy 67.2%. ([[feedback_actual_ml_not_fake]])
export type FontClassifierModel = {
  classes: string[]; features: string[]; mean: number[]; std: number[];
  W: number[][]; b: number[]; n: number; testAcc: number; trainedAt: string;
};
export const FONT_CLASSIFIER: FontClassifierModel = {
  "classes": [
    "sans",
    "serif",
    "display",
    "handwriting",
    "monospace"
  ],
  "features": [
    "xRatio",
    "monoRatio",
    "widthRatio",
    "capStretch",
    "serifProxy",
    "inkDensity"
  ],
  "mean": [
    0.70991,
    0.41001,
    0.80911,
    1.01588,
    0.4204,
    0.26033
  ],
  "std": [
    0.11448,
    0.21394,
    0.20451,
    0.23958,
    0.28902,
    0.1067
  ],
  "W": [
    [
      0.51366,
      0.70585,
      -0.36185,
      1.17072,
      -3.59771,
      1.1248
    ],
    [
      -0.55727,
      -0.39628,
      0.24594,
      0.92769,
      -0.09184,
      -0.15635
    ],
    [
      0.95254,
      0.02852,
      -0.27646,
      0.93264,
      -0.7398,
      1.14098
    ],
    [
      -0.74986,
      -1.93296,
      0.41419,
      -1.72303,
      2.92645,
      -2.04497
    ],
    [
      -0.15908,
      1.59488,
      -0.02183,
      -1.30802,
      1.50291,
      -0.06446
    ]
  ],
  "b": [
    0.15093,
    1.46493,
    1.18549,
    0.08069,
    -2.88204
  ],
  "n": 643,
  "testAcc": 0.6719,
  "trainedAt": "2026-06-25T19:12:03.088Z"
};
