// Trained correction model — AUTO-GENERATED by scripts/train-finetune.mjs. Do not hand-edit.
// 'trained:false' = no model yet (identity passthrough); the cap-match RULE runs alone until enough
// labeled TuneExamples are collected and the trainer fits a residual. ([[feedback_actual_ml_not_fake]])
export type LinModel = { w: number[]; b: number };
export type CorrectionModelFile = {
  trained: boolean;
  n: number;
  features?: string[];
  size?: LinModel; lh?: LinModel; track?: LinModel;
  rmseBefore?: Record<string, number>;
  rmseAfter?: Record<string, number>;
  trainedAt?: string;
};

export const CORRECTION_MODEL: CorrectionModelFile = {
  "trained": false,
  "n": 0
};
